export const TEST_CALL_API = 'TEST_CALL_API';
export const GET_TOKEN_LOGIN = 'GET_TOKEN_LOGIN';
export const VERIFY_TOKEN_FOR_GET_INFO = 'VERIFY_TOKEN_FOR_GET_INFO';
export const GET_ALL_COURSE = 'GET_ALL_COURSE';
export const QUERY_REGISTER_PRETEACHER = 'QUERY_REGISTER_PRETEACHER';

export const QUERY_GET_LIST_CLASS = 'QUERY_GET_LIST_CLASS';
export const QUERY_GET_LIST_TIME_SCHEDULE = 'QUERY_GET_LIST_TIME_SCHEDULE';

export const QUERY_GET_LIST_COURSE = 'QUERY_GET_LIST_COURSE';
export const QUERY_GET_DETAIL_COURSE = 'QUERY_GET_DETAIL_COURSE';
export const QUERY_CREATE_COURSE = 'QUERY_CREATE_COURSE';
export const QUERY_CREATE_LEVEL_COURSE = 'QUERY_CREATE_LEVEL_COURSE';
export const QUERY_UPDATE_LEVEL_COURSE = 'QUERY_UPDATE_LEVEL_COURSE';
export const QUERY_UPDATE_COURSE = 'QUERY_UPDATE_COURSE';

export const QUERY_CREATE_CLASS = 'QUERY_CREATE_CLASS';

export const QUERY_GET_LOCATIONS = 'QUERY_GET_LOCATIONS';
export const QUERY_UPDATE_LOCATION = 'QUERY_UPDATE_LOCATION';
export const QUERY_CREATE_LOCATION = 'QUERY_CREATE_LOCATION';

export const QUERY_GET_CURRENT_DATA_BOOK_TEACHER = 'QUERY_GET_CURRENT_DATA_BOOK_TEACHER';
export const QUERY_ADD_DATA_BOOK_TEACHER = 'QUERY_ADD_DATA_BOOK_TEACHER';

export const QUERY_DETAIL_CLASS = 'QUERY_DETAIL_CLASS';

export const QUERY_FIND_TEACHER_BY_EMAIL = 'QUERY_FIND_TEACHER_BY_EMAIL';

export const QUERY_HANDLE_TEACHER_IN_RECORD_BT = 'QUERY_HANDLE_TEACHER_IN_RECORD_BT';

export const QUERY_CLASS_SESSION = 'QUERY_CLASS_SESSION';
export const QUERY_CLASS_TEACHERPOINT = 'QUERY_CLASS_TEACHERPOINT';

export const QUERY_UPDATE_CLASS_BASIC_INFOR = 'QUERY_UPDATE_CLASS_BASIC_INFOR';

export const QUERY_GET_LIST_TEACHER = 'QUERY_GET_LIST_TEACHER';
export const QUERY_TEACHER_REGISTER_COURSE = 'QUERY_TEACHER_REGISTER_COURSE';
export const QUERY_UPDATE_TEACHER_REGISTER_COURSE = 'QUERY_UPDATE_TEACHER_REGISTER_COURSE';
export const QUERY_TEACHER_SCHEDULE = 'QUERY_TEACHER_SCHEDULE';
export const QUERY_TEACHER_DETAIL = 'QUERY_TEACHER_DETAIL';
export const QUERY_PRE_TEACHER = 'QUERY_PRE_TEACHER';
export const QUERY_ACCEPT_PRE_TEACHER = 'QUERY_ACCEPT_PRE_TEACHER';
export const QUERY_CLASS_TEACHER_REGISTER = 'QUERY_CLASS_TEACHER_REGISTER';
export const QUERY_UPDATE_TEACHER = 'QUERY_UPDATE_TEACHER';

export const QUERY_GET_ATTENDANCE_TEACHER = 'QUERY_GET_ATTENDANCE_TEACHER';

export const QUERY_GET_LIST_CLASS_FEEDBACK_ACTION = 'QUERY_GET_LIST_CLASS_FEEDBACK_ACTION';

export const QUERY_UPDATE_CLASS_FEEDBACK = 'QUERY_UPDATE_CLASS_FEEDBACK';

export const QUERY_GET_LIST_CLASS_IN_FEEDBACK = 'QUERY_GET_LIST_CLASS_IN_FEEDBACK';
export const QUERY_GET_LIST_GROUP_CLASS_IN_FEEDBACK = 'QUERY_GET_LIST_GROUP_CLASS_IN_FEEDBACK';
export const QUERY_RESPONSE_FEEDBACK = 'QUERY_RESPONSE_FEEDBACK';
export const QUERY_GET_LIST_RESPONSE_FEEDBACK = 'QUERY_GET_LIST_RESPONSE_FEEDBACK';
export const QUERY_GET_LIST_RESPONSE_FEEDBACK_FOR_TEACHER = 'QUERY_GET_LIST_RESPONSE_FEEDBACK_FOR_TEACHER';

export const QUERY_GET_LIST_DATA_RECRUITMENT = 'QUERY_GET_LIST_DATA_RECRUITMENT';
export const QUERY_GET_DETAIL_CANDIDATE = 'QUERY_GET_DETAIL_CANDIDATE';
export const QUERY_CREATE_CANDIDATE = 'QUERY_CREATE_CANDIDATE';
export const QUERY_UPDATE_CANDIDATE = 'QUERY_UPDATE_CANDIDATE';
export const QUERY_ROUND_PROCESS_CANDIDATE = 'QUERY_ROUND_PROCESS_CANDIDATE';
export const QUERY_ROUND_COMMENTS_CANDIDATE = 'QUERY_ROUND_COMMENTS_CANDIDATE';
export const QUERY_ROUND_CREATE_COMMENTS_CANDIDATE = 'QUERY_ROUND_CREATE_COMMENTS_CANDIDATE';
export const QUERY_UPDATE_INFO_ROUND_PROCESS_CANDIDATE = 'QUERY_UPDATE_INFO_ROUND_PROCESS_CANDIDATE';
export const QUERY_CREATE_INFO_ROUND_PROCESS_CANDIDATE = 'QUERY_CREATE_INFO_ROUND_PROCESS_CANDIDATE';

export const QUERY_GET_ALL_TE = 'QUERY_GET_ALL_TE';

export const QUERY_MAIL_TEMPLATE = 'QUERY_MAIL_TEMPLATE';
export const QUERY_CREATE_MAIL_TEMPLATE = 'QUERY_CREATE_MAIL_TEMPLATE';
export const QUERY_UPDATE_MAIL_TEMPLATE = 'QUERY_UPDATE_MAIL_TEMPLATE';

export const QUERY_MAILER = 'QUERY_MAILER';

export const QUERY_CHECK_CANDIDATE_INFO = 'QUERY_CHECK_CANDIDATE_INFO';
export const QUERY_CHECK_CLAUTID_INFO = 'QUERY_CHECK_CLAUTID_INFO';
export const QUERY_REGISTER_CLAUTID = 'QUERY_REGISTER_CLAUTID';
export const QUERY_CREATE_FEEDBACK_CLAUTID = 'QUERY_CREATE_FEEDBACK_CLAUTID';
export const QUERY_GET_FEEDBACK_CLAUTID = 'QUERY_GET_FEEDBACK_CLAUTID';
export const QUERY_UPDATE_RECORD_CLAUTID = 'QUERY_UPDATE_RECORD_CLAUTID';
export const QUERY_CALENDAR_TEST = 'QUERY_CALENDAR_TEST';

export const QUERY_GENERATE_ATTENDANCE_TEACHER = 'QUERY_GENERATE_ATTENDANCE_TEACHER';

export const QUERY_GET_AREA = 'QUERY_GET_AREA';
export const QUERY_CREATE_AREA = 'QUERY_CREATE_AREA';
export const QUERY_UPDATE_AREA = 'QUERY_UPDATE_AREA';

export const QUERY_GET_TIME_SCHEDULE = 'QUERY_GET_TIME_SCHEDULE';

export const QUERY_PREDICT_CANDiDATE = 'QUERY_PREDICT_CANDiDATE';

export const QUERY_RESET_PASSWORD = 'QUERY_RESET_PASSWORD';
export const QUERY_REQUEST_RESET_PASSWORD = 'QUERY_REQUEST_RESET_PASSWORD';

export const QUERY_GET_LIST_DOCUMENT = 'QUERY_GET_LIST_DOCUMENT';
export const QUERY_CREATE_DOCUMENT = 'QUERY_CREATE_DOCUMENT';
export const QUERY_DELETE_DOCUMENT = 'QUERY_DELETE_DOCUMENT';
export const QUERY_UPDATE_DOCUMENT = 'QUERY_UPDATE_DOCUMENT';
export const QUERY_GET_DETAIL_DOCUMENT = 'QUERY_GET_DETAIL_DOCUMENT';

export const QUERY_CREATE_FILE = 'QUERY_CREATE_FILE';
export const QUERY_GET_LIST_FILE = 'QUERY_GET_LIST_FILE';
export const QUERY_UPDATE_FILE = 'QUERY_UPDATE_FILE';
export const QUERY_DELETE_FILE = 'QUERY_DELETE_FILE';

export const QUERY_TE_BY_ID = 'QUERY_TE_BY_ID';
export const QUERY_UPDATE_TE_BY_ID = 'QUERY_UPDATE_TE_BY_ID';

export const QUERY_GET_LIST_FOLDER = 'QUERY_GET_LIST_FOLDER';
export const QUERY_CREATE_FOLDER = 'QUERY_CREATE_FOLDER';
export const QUERY_UPDATE_FOLDER = 'QUERY_UPDATE_FOLDER';
export const QUERY_DELETE_FOLDER = 'QUERY_DELETE_FOLDER';

export const SOCKET_CONNECTION = 'SOCKET_CONNECTION';

export const GET_LIST_COLLECTION_TEST = 'GET_LIST_COLLECTION_TEST';
export const CREATE_COLLECTION_TEST = 'CREATE_COLLECTION_TEST';
export const CREATE_QUESTION_QUIZ = 'CREATE_QUESTION_QUIZ';
export const GET_LIST_QUESTION = 'GET_LIST_QUESTION';
export const SAVE_ROOM_QUIZZ_TEST = 'SAVE_ROOM_QUIZZ_TEST';
export const STUDENT_JOIN_ROOM_QUIZZ_TEST = 'STUDENT_JOIN_ROOM_QUIZZ_TEST';

export const CREATE_REQUEST_ON_LEAVE = 'CREATE_REQUEST_ON_LEAVE';
export const GET_LIST_REQUEST_ON_LEAVE = 'GET_LIST_REQUEST_ON_LEAVE';